# Default htscodecs.mk generated by Makefile
include $(HTSPREFIX)htscodecs_bundled.mk
# Compiler probe results, generated by ./hts_probe_cc.sh
HTS_CFLAGS_SSSE3 =
HTS_BUILD_SSSE3 = 1
HTS_CFLAGS_POPCNT =
HTS_BUILD_POPCNT = 1
HTS_CFLAGS_SSE4_1 =
HTS_BUILD_SSE4_1 = 1
HTS_CFLAGS_SSE4 = $(HTS_CFLAGS_SSSE3) $(HTS_CFLAGS_POPCNT) $(HTS_CFLAGS_SSE4_1)
HTS_CFLAGS_AVX2 = -mavx2
HTS_BUILD_AVX2 = 1
HTS_CFLAGS_AVX512 = -mavx512f
HTS_BUILD_AVX512 = 1
