test_multiqc:
	rm -rf multiqc_data*
	rm -rf multiqc_report*.html
	/secondary/projects/laird/projects/2017_11_09_WZ_anaconda_python3.6/anaconda3/bin/multiqc /secondary/projects/laird/projects/2018_05_02_Wanding_tools/multiqc-develop/MultiQC_TestData/data/modules/biscuit/test_data
